-- Cleanup email tables for re-run
DROP VIEW IF EXISTS "vw_DailyEmailVolume" CASCADE;
DROP VIEW IF EXISTS "vw_EmailStatsByType" CASCADE;
DROP FUNCTION IF EXISTS email_process_bounce(UUID, TEXT, TEXT, TEXT) CASCADE;
DROP FUNCTION IF EXISTS email_update_status(UUID, TEXT, TEXT) CASCADE;
DROP FUNCTION IF EXISTS email_record_event(CITEXT, TEXT, TEXT, UUID, TEXT, JSONB) CASCADE;
DROP FUNCTION IF EXISTS email_is_suppressed(CITEXT) CASCADE;
DROP FUNCTION IF EXISTS generate_mailbox_full_address() CASCADE;
DROP TABLE IF EXISTS "EmailSuppressionList" CASCADE;
DROP TABLE IF EXISTS "EmailBounces" CASCADE;
DROP TABLE IF EXISTS "EmailMailboxes" CASCADE;
DROP TABLE IF EXISTS "EmailDomains" CASCADE;
DROP TABLE IF EXISTS "EmailTemplates" CASCADE;
DROP TABLE IF EXISTS "EmailEvents" CASCADE;
