# =============================================================================
# COST-FIRST ROUTING STRATEGY
# =============================================================================
"""
Implements a cost-first routing strategy that prioritizes inexpensive,
deterministic classification before invoking any language model.

This module ensures token usage is minimized at the routing stage by:
1. Evaluating ZERO-TOKEN rule-based triggers first
2. Only invoking minimal LLM classifier if rules are insufficient
3. Requiring explicit justification for escalation to higher tiers

CLASSIFICATION ORDER (cheap to expensive):
1. Zero-token: Keyword detection, pattern matching, length thresholds
2. Zero-token: Persona role requirements, contextual flags
3. Zero-token: Combined rule-based confidence scoring
4. (Only if needed): Minimal LLM classifier with constrained prompt

CRITICAL INVARIANTS:
1. Rule-based logic is ALWAYS evaluated first (zero tokens)
2. LLM classifier is ONLY invoked if confidence is below threshold
3. Classifier prompt is minimal and returns fixed, machine-readable output
4. No user-facing text is ever generated by the classifier
5. Higher models require explicit justification from classification
"""

import logging
import re
from dataclasses import dataclass, field
from datetime import datetime
from enum import Enum
from typing import Any, Callable, Dict, List, Optional, Tuple

from .classifier import (
    ClassificationResult,
    IntentCategory,
    ComplexityLevel,
    RiskLevel,
)
from .models import ModelTier

logger = logging.getLogger(__name__)


# =============================================================================
# CLASSIFICATION SOURCE
# =============================================================================

class ClassificationSource(Enum):
    """
    Source of the classification decision.

    Used to track whether classification was zero-token (cheap)
    or required LLM invocation (more expensive).
    """
    ZERO_TOKEN_KEYWORD = "zero_token_keyword"
    ZERO_TOKEN_PATTERN = "zero_token_pattern"
    ZERO_TOKEN_LENGTH = "zero_token_length"
    ZERO_TOKEN_CONTEXT = "zero_token_context"
    ZERO_TOKEN_COMBINED = "zero_token_combined"
    MINIMAL_LLM = "minimal_llm"
    FALLBACK = "fallback"


# =============================================================================
# CHEAP CLASSIFICATION RESULT
# =============================================================================

@dataclass
class CheapClassificationResult:
    """
    Result of cost-first classification.

    This extends ClassificationResult with cost-first specific metadata.
    """
    # Base classification
    classification: ClassificationResult = None

    # Cost-first metadata
    source: ClassificationSource = ClassificationSource.FALLBACK
    zero_token_attempted: bool = True
    zero_token_succeeded: bool = False
    llm_invoked: bool = False

    # Confidence tracking
    rule_confidence: float = 0.0  # Confidence from rule-based classification
    final_confidence: float = 0.0  # Final confidence after all stages

    # Cost metrics
    tokens_used: int = 0  # Tokens used for classification (0 if rule-based)
    estimated_cost_saved: float = 0.0  # Estimated cost saved vs always using LLM

    # Justification
    escalation_reason: Optional[str] = None  # Why LLM was needed (if any)
    tier_justification: str = ""  # Why this tier was selected

    # Timing
    classification_time_ms: float = 0.0
    classified_at: str = field(default_factory=lambda: datetime.now().isoformat())

    def to_dict(self) -> Dict[str, Any]:
        """Convert to dictionary."""
        return {
            "classification": self.classification.to_dict() if self.classification else None,
            "cost_first": {
                "source": self.source.value,
                "zero_token_attempted": self.zero_token_attempted,
                "zero_token_succeeded": self.zero_token_succeeded,
                "llm_invoked": self.llm_invoked,
            },
            "confidence": {
                "rule_based": self.rule_confidence,
                "final": self.final_confidence,
            },
            "cost": {
                "tokens_used": self.tokens_used,
                "estimated_cost_saved": self.estimated_cost_saved,
            },
            "justification": {
                "escalation_reason": self.escalation_reason,
                "tier_justification": self.tier_justification,
            },
            "timing": {
                "classification_time_ms": self.classification_time_ms,
                "classified_at": self.classified_at,
            },
        }


# =============================================================================
# ZERO-TOKEN CLASSIFIER
# =============================================================================

@dataclass
class ZeroTokenConfig:
    """Configuration for zero-token classification."""

    # Confidence thresholds
    high_confidence_threshold: float = 0.85  # Very confident, skip LLM
    medium_confidence_threshold: float = 0.65  # Moderately confident
    low_confidence_threshold: float = 0.50  # Need LLM verification

    # Length thresholds
    very_short_message_threshold: int = 10  # Likely greeting/ack
    short_message_threshold: int = 50  # Likely simple question
    long_message_threshold: int = 300  # Likely complex request
    very_long_message_threshold: int = 500  # Very complex

    # Pattern match requirements
    require_multiple_patterns: bool = False  # Require multiple pattern matches
    pattern_match_boost: float = 0.15  # Confidence boost per pattern match

    # Keyword match requirements
    keyword_match_boost: float = 0.10  # Confidence boost per keyword


class ZeroTokenClassifier:
    """
    Zero-token classifier using deterministic rules only.

    This classifier uses NO LLM tokens. It relies entirely on:
    - Keyword detection
    - Pattern matching (regex)
    - Message length thresholds
    - Persona role requirements
    - Contextual flags from activation state

    CRITICAL: This must be the FIRST classification step.
    """

    def __init__(self, config: ZeroTokenConfig = None):
        """Initialize the zero-token classifier."""
        self.config = config or ZeroTokenConfig()

        # Compile keyword sets for O(1) lookup
        self._compile_keywords()

        # Compile regex patterns
        self._compile_patterns()

    def _compile_keywords(self):
        """Compile keyword sets for efficient lookup."""
        # ECONOMY TIER KEYWORDS (instant match -> economy)
        self.economy_keywords = {
            # Greetings
            "hi", "hello", "hey", "howdy", "greetings", "sup", "yo",
            "morning", "afternoon", "evening",
            # Acknowledgments
            "ok", "okay", "thanks", "thank", "yes", "no", "sure",
            "alright", "understood", "got", "gotcha",
            # Simple questions
            "where", "when", "who", "which",
        }

        # STANDARD TIER KEYWORDS (suggest standard if found)
        self.standard_keywords = {
            # Teaching
            "teach", "explain", "understand", "learn", "study",
            "meaning", "interpret", "describe", "elaborate",
            # Pastoral
            "struggling", "worried", "anxious", "afraid", "scared",
            "help", "guidance", "advice", "pray", "prayer",
            "encourage", "comfort", "support",
            # Scripture application
            "apply", "application", "verse", "scripture", "bible",
            "passage", "chapter", "book",
        }

        # PREMIUM TIER KEYWORDS (instant escalation -> premium)
        self.premium_keywords = {
            # Doctrinal
            "doctrine", "doctrinal", "theology", "theological",
            "heresy", "heretical", "orthodox", "orthodoxy",
            "trinity", "trinitarian", "calvinist", "arminian",
            "predestination", "election", "atonement",
            "justification", "sanctification", "soteriology",
            "eschatology", "rapture", "tribulation", "millennium",
            # Crisis
            "crisis", "emergency", "urgent", "suicide", "suicidal",
            "abuse", "abused", "violence", "violent",
            "dying", "death", "funeral", "grief",
            "addiction", "addict", "alcoholic", "overdose",
            # Sensitive
            "divorce", "divorcing", "affair", "infidelity",
            "homosexual", "homosexuality", "lgbt", "transgender",
            "abortion", "euthanasia",
            # Leadership
            "church", "elder", "deacon", "pastor",
            "discipline", "excommunication", "membership",
            # Ethics
            "ethical", "moral", "dilemma", "sin", "sinful",
        }

        # IMMEDIATE ESCALATION KEYWORDS (always premium, no questions)
        self.critical_keywords = {
            "suicide", "suicidal", "kill", "killing",
            "abuse", "abused", "abuser",
            "emergency", "crisis", "urgent",
            "heresy", "heretical", "false",
        }

    def _compile_patterns(self):
        """Compile regex patterns for efficient matching."""
        # ECONOMY PATTERNS (high confidence -> economy)
        self.economy_patterns = [
            # Pure greetings
            re.compile(r"^(hi|hello|hey|howdy|greetings)[\s!.,?]*$", re.I),
            re.compile(r"^good\s+(morning|afternoon|evening|day)[\s!.,?]*$", re.I),
            # Pure acknowledgments
            re.compile(r"^(ok|okay|yes|no|sure|thanks|thank you)[\s!.,?]*$", re.I),
            re.compile(r"^(got it|understood|alright|sounds good)[\s!.,?]*$", re.I),
            # Simple questions
            re.compile(r"^what time", re.I),
            re.compile(r"^where (is|are|can)", re.I),
        ]

        # STANDARD PATTERNS (suggest standard)
        self.standard_patterns = [
            # Teaching requests
            re.compile(r"(teach|explain|help)\s+(me|us)", re.I),
            re.compile(r"what\s+(does|is)\s+.+\s+mean", re.I),
            re.compile(r"can\s+you\s+explain", re.I),
            # Pastoral indicators
            re.compile(r"i('m|\s+am)\s+(struggling|worried|anxious)", re.I),
            re.compile(r"(pray|prayer)\s+(for|with)", re.I),
        ]

        # PREMIUM PATTERNS (escalate to premium)
        self.premium_patterns = [
            # Doctrinal questions
            re.compile(r"(what|how)\s+.*(doctrine|theology|believe)", re.I),
            re.compile(r"(trinity|predestination|election|atonement)", re.I),
            # Crisis indicators
            re.compile(r"(suicide|suicidal|kill\s+(my)?self)", re.I),
            re.compile(r"(abuse|abused|abuser)", re.I),
            # Leadership decisions
            re.compile(r"(church|ministry)\s+(leadership|decision)", re.I),
            re.compile(r"(should|how)\s+(we|i|the\s+church)", re.I),
            # Sensitive topics
            re.compile(r"(divorce|divorcing|affair)", re.I),
            re.compile(r"(homosexual|lgbt|transgender)", re.I),
        ]

    def classify(
        self,
        message: str,
        context: Dict[str, Any] = None,
    ) -> Tuple[CheapClassificationResult, bool]:
        """
        Attempt zero-token classification.

        Args:
            message: The user's message
            context: Optional context (persona, history, etc.)

        Returns:
            Tuple of (CheapClassificationResult, is_confident)
            is_confident indicates if classification is confident enough
            to skip LLM verification.
        """
        start_time = datetime.now()
        context = context or {}

        result = CheapClassificationResult(
            classification=ClassificationResult(message_length=len(message)),
            zero_token_attempted=True,
        )

        # Track confidence from different sources
        confidence_sources = []

        # Step 1: Check message length (very cheap heuristic)
        length_tier, length_conf = self._classify_by_length(message)
        if length_conf > 0:
            confidence_sources.append(("length", length_tier, length_conf))

        # Step 2: Check for critical keywords (instant escalation)
        critical_match = self._check_critical_keywords(message)
        if critical_match:
            result.classification.intent = IntentCategory.CRISIS_GUIDANCE
            result.classification.risk = RiskLevel.CRITICAL
            result.classification.complexity = ComplexityLevel.HIGH
            result.classification.intent_confidence = 0.99
            result.source = ClassificationSource.ZERO_TOKEN_KEYWORD
            result.zero_token_succeeded = True
            result.rule_confidence = 0.99
            result.final_confidence = 0.99
            result.tier_justification = f"Critical keyword detected: {critical_match}"
            result.classification.detected_keywords.append(critical_match)
            self._finalize_timing(result, start_time)
            return result, True  # Very confident

        # Step 3: Check economy patterns (exact matches for greetings, etc.)
        economy_match, economy_conf = self._check_economy_patterns(message)
        if economy_match and economy_conf >= self.config.high_confidence_threshold:
            result.classification.intent = economy_match
            result.classification.risk = RiskLevel.LOW
            result.classification.complexity = ComplexityLevel.LOW
            result.classification.intent_confidence = economy_conf
            result.source = ClassificationSource.ZERO_TOKEN_PATTERN
            result.zero_token_succeeded = True
            result.rule_confidence = economy_conf
            result.final_confidence = economy_conf
            result.tier_justification = f"Economy pattern matched with high confidence"
            self._finalize_timing(result, start_time)
            return result, True

        # Step 4: Check premium keywords (escalation triggers)
        premium_keywords = self._check_premium_keywords(message)
        if premium_keywords:
            # Determine specific intent based on keywords
            intent, risk = self._determine_premium_intent(premium_keywords)
            result.classification.intent = intent
            result.classification.risk = risk
            result.classification.complexity = ComplexityLevel.HIGH
            result.classification.intent_confidence = 0.85
            result.classification.detected_keywords = premium_keywords
            result.source = ClassificationSource.ZERO_TOKEN_KEYWORD
            result.zero_token_succeeded = True
            result.rule_confidence = 0.85
            result.final_confidence = 0.85
            result.tier_justification = f"Premium keywords detected: {', '.join(premium_keywords[:3])}"
            self._finalize_timing(result, start_time)
            return result, True

        # Step 5: Check premium patterns
        premium_match, premium_conf = self._check_premium_patterns(message)
        if premium_match and premium_conf >= self.config.medium_confidence_threshold:
            result.classification.intent = premium_match
            result.classification.risk = RiskLevel.HIGH
            result.classification.complexity = ComplexityLevel.HIGH
            result.classification.intent_confidence = premium_conf
            result.source = ClassificationSource.ZERO_TOKEN_PATTERN
            result.zero_token_succeeded = True
            result.rule_confidence = premium_conf
            result.final_confidence = premium_conf
            self._finalize_timing(result, start_time)
            return result, premium_conf >= self.config.high_confidence_threshold

        # Step 6: Check standard keywords and patterns
        standard_keywords = self._check_standard_keywords(message)
        standard_match, standard_conf = self._check_standard_patterns(message)

        if standard_keywords or (standard_match and standard_conf > 0.5):
            # Combine keyword and pattern confidence
            combined_conf = max(
                len(standard_keywords) * self.config.keyword_match_boost + 0.5,
                standard_conf
            )
            combined_conf = min(combined_conf, 0.85)

            result.classification.intent = standard_match or IntentCategory.TEACHING_REQUEST
            result.classification.risk = RiskLevel.MEDIUM
            result.classification.complexity = ComplexityLevel.MEDIUM
            result.classification.intent_confidence = combined_conf
            result.classification.detected_keywords = standard_keywords
            result.source = ClassificationSource.ZERO_TOKEN_COMBINED
            result.zero_token_succeeded = combined_conf >= self.config.medium_confidence_threshold
            result.rule_confidence = combined_conf
            result.final_confidence = combined_conf
            self._finalize_timing(result, start_time)
            return result, combined_conf >= self.config.high_confidence_threshold

        # Step 7: Check economy keywords (fallback for simple requests)
        economy_keywords = self._check_economy_keywords(message)
        if economy_keywords and len(message) < self.config.short_message_threshold:
            conf = min(0.70, 0.50 + len(economy_keywords) * 0.1)
            result.classification.intent = IntentCategory.SIMPLE_QUESTION
            result.classification.risk = RiskLevel.LOW
            result.classification.complexity = ComplexityLevel.LOW
            result.classification.intent_confidence = conf
            result.classification.detected_keywords = economy_keywords
            result.source = ClassificationSource.ZERO_TOKEN_KEYWORD
            result.zero_token_succeeded = conf >= self.config.medium_confidence_threshold
            result.rule_confidence = conf
            result.final_confidence = conf
            self._finalize_timing(result, start_time)
            return result, conf >= self.config.medium_confidence_threshold

        # Step 8: Apply context-based adjustments
        context_tier, context_conf = self._apply_context(message, context)
        if context_tier and context_conf > 0:
            confidence_sources.append(("context", context_tier, context_conf))

        # Step 9: Combine all confidence sources
        if confidence_sources:
            best_source = max(confidence_sources, key=lambda x: x[2])
            result.source = ClassificationSource.ZERO_TOKEN_COMBINED
            result.rule_confidence = best_source[2]
            result.final_confidence = best_source[2]

            # Set intent based on best source tier
            if best_source[0] == "length":
                result.classification.intent = IntentCategory.SIMPLE_QUESTION
            result.zero_token_succeeded = best_source[2] >= self.config.low_confidence_threshold

            self._finalize_timing(result, start_time)
            return result, best_source[2] >= self.config.medium_confidence_threshold

        # No confident classification - will need LLM
        result.source = ClassificationSource.FALLBACK
        result.zero_token_succeeded = False
        result.rule_confidence = 0.3
        result.final_confidence = 0.3
        result.escalation_reason = "No rule-based classification achieved sufficient confidence"
        self._finalize_timing(result, start_time)
        return result, False

    def _classify_by_length(self, message: str) -> Tuple[Optional[ModelTier], float]:
        """Classify based on message length."""
        length = len(message.strip())

        if length <= self.config.very_short_message_threshold:
            return ModelTier.ECONOMY, 0.80  # Very short = likely greeting/ack

        if length <= self.config.short_message_threshold:
            return ModelTier.ECONOMY, 0.60  # Short = likely simple

        if length >= self.config.very_long_message_threshold:
            return ModelTier.STANDARD, 0.50  # Very long = likely complex

        if length >= self.config.long_message_threshold:
            return ModelTier.STANDARD, 0.40  # Long = possibly complex

        return None, 0.0

    def _check_critical_keywords(self, message: str) -> Optional[str]:
        """Check for critical keywords that require immediate escalation."""
        message_lower = message.lower()
        words = set(re.findall(r'\b\w+\b', message_lower))

        for keyword in self.critical_keywords:
            if keyword in words:
                return keyword
        return None

    def _check_economy_patterns(self, message: str) -> Tuple[Optional[IntentCategory], float]:
        """Check economy-tier patterns."""
        for pattern in self.economy_patterns:
            if pattern.match(message):
                # Determine specific intent
                message_lower = message.lower()
                if any(g in message_lower for g in ["hi", "hello", "hey", "morning", "afternoon", "evening"]):
                    return IntentCategory.GREETING, 0.95
                if any(a in message_lower for a in ["ok", "okay", "thanks", "yes", "no", "understood"]):
                    return IntentCategory.ACKNOWLEDGMENT, 0.95
                return IntentCategory.SIMPLE_QUESTION, 0.85
        return None, 0.0

    def _check_premium_keywords(self, message: str) -> List[str]:
        """Check for premium-tier keywords."""
        message_lower = message.lower()
        words = set(re.findall(r'\b\w+\b', message_lower))
        return [kw for kw in self.premium_keywords if kw in words]

    def _check_premium_patterns(self, message: str) -> Tuple[Optional[IntentCategory], float]:
        """Check premium-tier patterns."""
        for pattern in self.premium_patterns:
            if pattern.search(message):
                return IntentCategory.DOCTRINAL_QUESTION, 0.80
        return None, 0.0

    def _check_standard_keywords(self, message: str) -> List[str]:
        """Check for standard-tier keywords."""
        message_lower = message.lower()
        words = set(re.findall(r'\b\w+\b', message_lower))
        return [kw for kw in self.standard_keywords if kw in words]

    def _check_standard_patterns(self, message: str) -> Tuple[Optional[IntentCategory], float]:
        """Check standard-tier patterns."""
        for pattern in self.standard_patterns:
            if pattern.search(message):
                # Determine specific intent
                if "pray" in message.lower():
                    return IntentCategory.PRAYER_REQUEST, 0.80
                if any(w in message.lower() for w in ["struggling", "worried", "anxious"]):
                    return IntentCategory.PASTORAL_GUIDANCE, 0.75
                return IntentCategory.TEACHING_REQUEST, 0.70
        return None, 0.0

    def _check_economy_keywords(self, message: str) -> List[str]:
        """Check for economy-tier keywords."""
        message_lower = message.lower()
        words = set(re.findall(r'\b\w+\b', message_lower))
        return [kw for kw in self.economy_keywords if kw in words]

    def _determine_premium_intent(self, keywords: List[str]) -> Tuple[IntentCategory, RiskLevel]:
        """Determine specific intent and risk from premium keywords."""
        # Check for crisis keywords
        crisis_keywords = {"crisis", "emergency", "urgent", "suicide", "abuse", "death"}
        if any(kw in crisis_keywords for kw in keywords):
            return IntentCategory.CRISIS_GUIDANCE, RiskLevel.CRITICAL

        # Check for doctrinal keywords
        doctrinal_keywords = {"doctrine", "theology", "trinity", "predestination", "heresy"}
        if any(kw in doctrinal_keywords for kw in keywords):
            return IntentCategory.DOCTRINAL_QUESTION, RiskLevel.HIGH

        # Check for leadership keywords
        leadership_keywords = {"church", "elder", "deacon", "pastor", "discipline"}
        if any(kw in leadership_keywords for kw in keywords):
            return IntentCategory.LEADERSHIP_DECISION, RiskLevel.HIGH

        # Check for ethical keywords
        ethical_keywords = {"ethical", "moral", "dilemma", "sin"}
        if any(kw in ethical_keywords for kw in keywords):
            return IntentCategory.ETHICAL_DILEMMA, RiskLevel.HIGH

        # Check for sensitive keywords
        sensitive_keywords = {"divorce", "homosexual", "abortion", "transgender"}
        if any(kw in sensitive_keywords for kw in keywords):
            return IntentCategory.SENSITIVE_MATTER, RiskLevel.HIGH

        # Default to doctrinal
        return IntentCategory.DOCTRINAL_QUESTION, RiskLevel.HIGH

    def _apply_context(
        self,
        message: str,
        context: Dict[str, Any],
    ) -> Tuple[Optional[ModelTier], float]:
        """Apply context-based adjustments."""
        # Persona role requirements
        persona_name = context.get("persona_name", "").lower()
        if persona_name in ["scholar", "theologian"]:
            # Scholarly personas may need higher tier more often
            return ModelTier.STANDARD, 0.40

        # Previous crisis flag
        if context.get("previous_crisis"):
            return ModelTier.PREMIUM, 0.60

        # User is leader flag
        if context.get("user_is_leader"):
            return ModelTier.STANDARD, 0.30

        return None, 0.0

    def _finalize_timing(self, result: CheapClassificationResult, start_time: datetime):
        """Finalize timing information."""
        end_time = datetime.now()
        result.classification_time_ms = (end_time - start_time).total_seconds() * 1000
        result.classified_at = end_time.isoformat()


# =============================================================================
# MINIMAL LLM CLASSIFIER
# =============================================================================

# The minimal classifier prompt - as short as possible
MINIMAL_CLASSIFIER_PROMPT = """Classify intent: R=routine, T=teaching, D=doctrine, C=crisis
Message: {message}
Output format: INTENT:X (X is one letter)"""

# Maximum tokens for classifier response
CLASSIFIER_MAX_TOKENS = 10


@dataclass
class MinimalClassifierConfig:
    """Configuration for minimal LLM classifier."""

    # Model to use (always the cheapest)
    model_id: str = "gpt-4o-mini"

    # Prompt configuration
    prompt_template: str = MINIMAL_CLASSIFIER_PROMPT
    max_tokens: int = CLASSIFIER_MAX_TOKENS

    # Response parsing
    valid_responses: List[str] = field(
        default_factory=lambda: ["R", "T", "D", "C"]
    )

    # Timeouts
    timeout_seconds: float = 5.0


class MinimalLLMClassifier:
    """
    Minimal LLM classifier for ambiguous cases.

    This classifier is ONLY invoked when zero-token classification
    fails to achieve sufficient confidence. It uses:
    - The cheapest available model
    - A minimal, tightly constrained prompt
    - Fixed, machine-readable output format
    - NO user-facing text generation

    CRITICAL: This should be invoked as rarely as possible.
    """

    # Intent mapping from classifier response
    INTENT_MAP = {
        "R": IntentCategory.ROUTINE_REQUEST,
        "T": IntentCategory.TEACHING_REQUEST,
        "D": IntentCategory.DOCTRINAL_QUESTION,
        "C": IntentCategory.CRISIS_GUIDANCE,
    }

    # Tier mapping from classifier response
    TIER_MAP = {
        "R": ModelTier.ECONOMY,
        "T": ModelTier.STANDARD,
        "D": ModelTier.PREMIUM,
        "C": ModelTier.PREMIUM,
    }

    # Risk mapping from classifier response
    RISK_MAP = {
        "R": RiskLevel.LOW,
        "T": RiskLevel.MEDIUM,
        "D": RiskLevel.HIGH,
        "C": RiskLevel.CRITICAL,
    }

    def __init__(
        self,
        config: MinimalClassifierConfig = None,
        call_llm: Callable = None,
    ):
        """
        Initialize the minimal classifier.

        Args:
            config: Classifier configuration
            call_llm: Function to call the LLM (message, model_id, max_tokens) -> response
        """
        self.config = config or MinimalClassifierConfig()
        self.call_llm = call_llm

    def classify(
        self,
        message: str,
        partial_result: CheapClassificationResult = None,
    ) -> CheapClassificationResult:
        """
        Classify using minimal LLM prompt.

        Args:
            message: The user's message
            partial_result: Partial result from zero-token classification

        Returns:
            CheapClassificationResult with LLM classification
        """
        start_time = datetime.now()

        # Initialize or update result
        if partial_result:
            result = partial_result
        else:
            result = CheapClassificationResult(
                classification=ClassificationResult(message_length=len(message))
            )

        result.llm_invoked = True
        result.source = ClassificationSource.MINIMAL_LLM

        # Check if we have a call_llm function
        if not self.call_llm:
            logger.warning("No call_llm function provided, using fallback")
            result.escalation_reason = "No LLM function available"
            self._apply_fallback(result)
            self._finalize_timing(result, start_time)
            return result

        try:
            # Build the minimal prompt
            prompt = self.config.prompt_template.format(
                message=message[:200]  # Truncate for cost
            )

            # Call the LLM
            response = self.call_llm(
                prompt,
                self.config.model_id,
                self.config.max_tokens,
            )

            # Parse the response
            intent_code = self._parse_response(response)

            if intent_code and intent_code in self.INTENT_MAP:
                # Successful classification
                result.classification.intent = self.INTENT_MAP[intent_code]
                result.classification.risk = self.RISK_MAP[intent_code]
                result.classification.complexity = (
                    ComplexityLevel.LOW if intent_code == "R"
                    else ComplexityLevel.MEDIUM if intent_code == "T"
                    else ComplexityLevel.HIGH
                )
                result.classification.intent_confidence = 0.80
                result.final_confidence = 0.80
                result.tier_justification = f"LLM classified as '{intent_code}'"

                # Estimate tokens used
                result.tokens_used = len(prompt.split()) + 5  # Rough estimate
            else:
                # Failed to parse response
                logger.warning(f"Failed to parse LLM response: {response}")
                result.escalation_reason = f"Failed to parse LLM response: {response}"
                self._apply_fallback(result)

        except Exception as e:
            logger.error(f"LLM classification failed: {e}")
            result.escalation_reason = f"LLM error: {str(e)}"
            self._apply_fallback(result)

        self._finalize_timing(result, start_time)
        return result

    def _parse_response(self, response: str) -> Optional[str]:
        """Parse the LLM response to extract intent code."""
        if not response:
            return None

        # Look for pattern INTENT:X
        import re
        match = re.search(r"INTENT:([RTDC])", response.upper())
        if match:
            return match.group(1)

        # Fallback: look for single letter
        response_clean = response.strip().upper()
        if len(response_clean) == 1 and response_clean in "RTDC":
            return response_clean

        return None

    def _apply_fallback(self, result: CheapClassificationResult):
        """Apply fallback classification when LLM fails."""
        # Default to standard tier for safety
        result.classification.intent = IntentCategory.UNKNOWN
        result.classification.risk = RiskLevel.MEDIUM
        result.classification.complexity = ComplexityLevel.MEDIUM
        result.classification.intent_confidence = 0.50
        result.final_confidence = 0.50
        result.tier_justification = "Fallback to standard tier (LLM failed)"

    def _finalize_timing(self, result: CheapClassificationResult, start_time: datetime):
        """Finalize timing information."""
        end_time = datetime.now()
        llm_time = (end_time - start_time).total_seconds() * 1000
        result.classification_time_ms += llm_time
        result.classified_at = end_time.isoformat()


# =============================================================================
# COST-FIRST CLASSIFIER (MAIN INTERFACE)
# =============================================================================

class CostFirstClassifier:
    """
    Main cost-first classifier that orchestrates the classification pipeline.

    This is the primary interface for cheap-first routing. It:
    1. ALWAYS attempts zero-token classification first
    2. Only invokes LLM if confidence is insufficient
    3. Tracks cost metrics and savings

    USAGE:
        classifier = CostFirstClassifier()
        result = classifier.classify("What is the meaning of John 3:16?")
        tier = result.classification.intent  # Use for routing
    """

    def __init__(
        self,
        zero_token_config: ZeroTokenConfig = None,
        minimal_llm_config: MinimalClassifierConfig = None,
        call_llm: Callable = None,
        confidence_threshold: float = 0.70,
    ):
        """
        Initialize the cost-first classifier.

        Args:
            zero_token_config: Config for zero-token classifier
            minimal_llm_config: Config for minimal LLM classifier
            call_llm: Function to call LLM (if needed)
            confidence_threshold: Threshold for skipping LLM
        """
        self.zero_token = ZeroTokenClassifier(zero_token_config)
        self.minimal_llm = MinimalLLMClassifier(minimal_llm_config, call_llm)
        self.confidence_threshold = confidence_threshold

        # Statistics
        self._stats = {
            "total_classifications": 0,
            "zero_token_successes": 0,
            "llm_invocations": 0,
            "total_tokens_used": 0,
            "estimated_savings": 0.0,
        }

    def classify(
        self,
        message: str,
        context: Dict[str, Any] = None,
    ) -> CheapClassificationResult:
        """
        Classify a message using cost-first strategy.

        Args:
            message: The user's message
            context: Optional context

        Returns:
            CheapClassificationResult
        """
        self._stats["total_classifications"] += 1

        # Step 1: ALWAYS try zero-token first
        result, is_confident = self.zero_token.classify(message, context)

        if is_confident or result.final_confidence >= self.confidence_threshold:
            # Zero-token succeeded - no LLM needed
            self._stats["zero_token_successes"] += 1
            result.estimated_cost_saved = self._estimate_savings()
            return result

        # Step 2: Zero-token insufficient - invoke minimal LLM
        logger.info(
            f"Zero-token confidence {result.final_confidence:.2f} below threshold "
            f"{self.confidence_threshold:.2f}, invoking minimal LLM"
        )

        result = self.minimal_llm.classify(message, result)
        self._stats["llm_invocations"] += 1
        self._stats["total_tokens_used"] += result.tokens_used

        return result

    def _estimate_savings(self) -> float:
        """Estimate cost saved by using zero-token classification."""
        # Rough estimate: LLM classification costs ~50 tokens
        # If we skip LLM, we save those tokens
        return 50 * 0.00001  # Rough cost per token

    def get_statistics(self) -> Dict[str, Any]:
        """Get classification statistics."""
        stats = self._stats.copy()
        if stats["total_classifications"] > 0:
            stats["zero_token_rate"] = (
                stats["zero_token_successes"] / stats["total_classifications"]
            )
            stats["llm_invocation_rate"] = (
                stats["llm_invocations"] / stats["total_classifications"]
            )
        return stats

    def reset_statistics(self):
        """Reset classification statistics."""
        self._stats = {
            "total_classifications": 0,
            "zero_token_successes": 0,
            "llm_invocations": 0,
            "total_tokens_used": 0,
            "estimated_savings": 0.0,
        }


# =============================================================================
# GLOBAL INSTANCE
# =============================================================================

_global_cost_first_classifier: Optional[CostFirstClassifier] = None


def get_cost_first_classifier() -> CostFirstClassifier:
    """Get the global cost-first classifier."""
    global _global_cost_first_classifier
    if _global_cost_first_classifier is None:
        _global_cost_first_classifier = CostFirstClassifier()
    return _global_cost_first_classifier


def set_cost_first_classifier(classifier: CostFirstClassifier):
    """Set the global cost-first classifier."""
    global _global_cost_first_classifier
    _global_cost_first_classifier = classifier


def reset_cost_first_classifier():
    """Reset the global cost-first classifier."""
    global _global_cost_first_classifier
    _global_cost_first_classifier = None
